# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Shubham
tagline:          'Personal Blog'
description:      'Ph.D. Candidate in Operations Management | Robert H. Smith School of Business'
url:              https://shubham2iitd.github.io/
baseurl:          /

author:
  name:           ''
  url:            ''

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shadowfax92/sakshat
