# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Shubham
tagline:          'A Jekyll theme'
description:      'Ph.D. Candidate in Operations Management | Robert H. Smith School of Business'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           ''
  url:            ''

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
